apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    name: mariadb-service
    app: footwear-webstore-app
spec:
  selector:
    app: footwear-webstore-app
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  externalIPs:
  - $DB_SERVER_IP
