apiVersion: v1
kind: Service
metadata:
  name: display-service
  labels:
    name: display-service
    app: footwear-webstore-app
spec:
  selector:
    name: display-pod
    app: footwear-webstore-app
  ports:
  - port: 80
    targetPort: 80