manifest_dir: /home/ubuntu/manifests/

manifests_to_copy: 
  - route-deploy.yml
  - display-deploy.yml
  - buy-deploy.yml

db_manifest:
  template: db-external-service.j2
  svc: db-external-service.yml

footwear_manifests:
  - db-external-service.yml
  - display-deploy.yml
  - buy-deploy.yml
  - route-deploy.yml
