---
- name: Update apt
  apt:
    update_cache: yes

- name: Install docker
  apt:
    name: docker.io
    state: present
    
- name: Install microk8s
  snap:
    name: microk8s
    state: present
    classic: yes

- name: Add user to docker and microk8s group
  user:
    name: ubuntu
    state: present
    groups:
      - docker
      - microk8s

- name: Wait for microk8s to be ready
  command:
    cmd: microk8s status --wait-ready
  changed_when: false