---
- name: Setup microk8s
  hosts: multinode_cluster
  gather_facts: false

  tasks:
    - name: Install microk8s and prereqs
      import_tasks: microk8s-setup-tasks.yml

- name: Join Workers nodes to Master node
  gather_facts: false

  tasks:
    - name: Add worker node to cluster
      import_tasks: join-node-tasks.yml
      loop: "{{ groups['worker_nodes'] }}"

- name: Deploy Footwear and Enable Dashboard
  hosts: control_node
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Create manifests
      import_tasks: create-manifests-tasks.yml

    - name: Enable dashboard
      import_tasks: dashboard-tasks.yml
