---
- name: Setup MySQL Database
  hosts: database_server
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install mysql
      apt:
        name: "{{ pkgs }}"
        state: present
    
    - name: Ensure mysql is started and enabled
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create mysql user with privileges
      mysql_user:
        name: "{{ mysql_info.username }}"
        password: "{{ mysql_info.password }}"
        priv: '*.*:ALL,GRANT'
        host: '%'
        state: present
    
    - name: Download sql script
      copy:
        src: "{{ mysql_init_script.src }}/{{ mysql_init_script.file }}"
        dest: /tmp/
        mode: 0775
    
    - name: Create database
      mysql_db:
        name: "{{ mysql_info.database }}"
        state: present
    
    - name: Populate database
      mysql_db:
        name: all
        state: import
        target: /tmp/{{ mysql_init_script.file }}
    
    - name: Remove sql script
      file:
        state: absent
        path: /tmp/{{ mysql_init_script.file }}
    
    - name: Ensure mysql can be accessed from anywhere
      lineinfile:
         path: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
         backup: yes
      notify:
         - Restart mysql
         - Wait for mysql port

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
    
    - name: Wait for mysql port
      wait_for:
        port: 3306
        state: started
