apiVersion: v1
kind: Service
metadata:
  name: route-service
  labels:
    name: route-service
    app: footwear-webstore-app
spec:
  selector:
    name: route-pod
    app: footwear-webstore-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000