apiVersion: apps/v1
kind: Deployment
metadata:
  name: buy-deploy
  labels:
    name: buy-deploy
    app: footwear-webstore-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      name: buy-pod
      app: footwear-webstore-app
  template:
    metadata:
      name: buy-pod
      labels:
        name: buy-pod
        app: footwear-webstore-app
    spec:
      containers:
      - name: buy
        imagePullPolicy: IfNotPresent # Always
        image: piepielovers/footwear-web:buy
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "75m"
            memory: "158Mi"
          limits:
            memory: "158Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: buy-service
  labels:
    name: buy-service
    app: footwear-webstore-app
spec:
  selector:
    name: buy-pod
    app: footwear-webstore-app
  # type: ClusterIP
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: buy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: buy-deploy
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 95Mi
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
