apiVersion: apps/v1
kind: Deployment
metadata:
  name: display-deploy
  labels:
    name: display-deploy
    app: footwear-webstore-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      name: display-pod
      app: footwear-webstore-app
  template:
    metadata:
      name: display-pod
      labels:
        name: display-pod
        app: footwear-webstore-app
    spec:
      containers:
      - name: display
        imagePullPolicy: IfNotPresent # Always
        image: piepielovers/footwear-web:display
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "125m"
            memory: "256Mi"
          limits:
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: display-service
  labels:
    name: display-service
    app: footwear-webstore-app
spec:
  selector:
    name: display-pod
    app: footwear-webstore-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: display-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: display-deploy
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 179Mi
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
