version: "3.7"

services:
    database:
        container_name: db_pod
        image: "mariadb"
        restart: "always"
        volumes:
            - "./database:/docker-entrypoint-initdb.d"
        environment:
            MYSQL_ROOT_PASSWORD: "csc547cloud"
            MYSQL_DATABASE: "Products"
            MYSQL_USER: "csc547"
            MYSQL_PASSWORD: "csc547cloud"
        ports:
            - "3306:3306"

    display:
        container_name: display_pod
        image: "piepielovers/footwear-web:display"
        # build: 
        #     context: ./web/display
        restart: "always"
        # volumes:
        #     - "./web/display:/var/www/html"
        depends_on: 
            - database
        ports:
            - "8082:80"
        links:
            - database
    
    buy:
        container_name: buy_pod
        image: "piepielovers/footwear-web:buy"
        # build: 
        #     context: ./web/buy
        restart: "always"
        # volumes:
        #     - "./web/buy:/var/www/html"
        depends_on: 
            - database
        ports:
            - "8081:80"
        links:
            - database
    
    route:
        container_name: route_pod
        image: "piepielovers/footwear-web:route"
        # build: 
        #     context: ./web/route
        restart: "always"
        # volumes:
        #     - "./web/route:/var/www/html"
        depends_on: 
            - display
            - buy
        ports:
            - "8080:80"
        links:
            - display
            - buy