version: "3.7"

services:
    database:
        container_name: db_pod
        image: "mariadb"
        restart: "always"
        volumes:
            - "./database:/docker-entrypoint-initdb.d"
        environment:
            MYSQL_ROOT_PASSWORD: "CsCEcE547@Cloud"
            MYSQL_DATABASE: "Products"
            MYSQL_USER: "csc547"
            MYSQL_PASSWORD: "CsCEcE547@Cloud"
        ports:
            - "3306:3306"

    display:
        container_name: display_pod
        build: 
            context: ./web
        restart: "always"
        volumes:
            - "./web/display:/var/www/html"
        depends_on: 
            - database
        ports:
            - "8082:80"
        links:
            - database
    
    buy:
        container_name: buy_pod
        build: 
            context: ./web
        restart: "always"
        volumes:
            - "./web/buy:/var/www/html"
        depends_on: 
            - database
        ports:
            - "8081:80"
        links:
            - database
    
    route:
        container_name: route_pod
        build: 
            context: ./web
        restart: "always"
        volumes:
            - "./web/route:/var/www/html"
        depends_on: 
            - display
            - buy
        ports:
            - "8080:80"
        links:
            - display
            - buy