version: "3.7"

services:
    database:
        image: "mariadb"
        restart: "always"
        volumes:
            - "./database:/home/mariadb/data"
        environment:
            MYSQL_ROOT_PASSWORD: "CsCEcE547@Cloud"
            MYSQL_DATABASE: "Products"
            MYSQL_USER: "csc547"
            MYSQL_PASSWORD: "CsCEcE547@Cloud"

    display:
        image: "php:7.4.33-apache"
        restart: "always"
        volumes:
            - "./display:/home/display"
        depends_on: 
            - database
        ports:
            - "8080:80"
        links:
            - database
    
    buy:
        image: "php:7.4.33-apache"
        restart: "always"
        volumes:
            - "./buy:/home/buy"
        depends_on: 
            - database
        ports:
            - "8081:80"
        links:
            - database
    
    route:
        image: "php:7.4.33-apache"
        restart: "always"
        volumes:
            - "./route:/home/route"
        depends_on: 
            - database
        ports:
            - "8082:80"
        links:
            - database
